# Generated by Django 4.1.7 on 2023-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usernm", models.CharField(max_length=50)),
                ("bankaccid", models.CharField(default=10000, max_length=10)),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
    ]
