# Generated by Django 4.1.7 on 2023-03-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinetransaction", "0002_remove_payments_id_alter_payments_bankaccid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="bankaccid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
